    -- Enable RLS on all tables
    ALTER TABLE resource_types ENABLE ROW LEVEL SECURITY;
    ALTER TABLE municipality ENABLE ROW LEVEL SECURITY;
    ALTER TABLE users ENABLE ROW LEVEL SECURITY;
    ALTER TABLE status_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE resource ENABLE ROW LEVEL SECURITY;